apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: set-permissions
        image: alpine
        command: ["sh", "-c", "chown -R $UID:$GID /var/cache/nginx/client_temp"]
        securityContext:
          runAsUser: 0  # Optional: Run the init container as root
        volumeMounts:
        - mountPath: /var/cache/nginx
          name: nginx-persistent-storage
      containers:
      - name: nginx
        image: nginx
        # Your Nginx container spec
      volumes:
      - name: nginx-persistent-storage
        emptyDir: {}
